name: Problem or bug
description: Create a report to help us improve
labels: [ Potential bug, Verification ]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs or problems only!
        If you have a question, please use the template for questions.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues and no issue is describing my issue
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing. Tell us what you were trying to do and what happened.
        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: jscontroller_version
    validations:
      required: true
    attributes:
      label: Version of the JS controller
      placeholder: e.g. 3.2.16, 3.3.15
      description: >
        See "Hosts" tab
  - type: input
    id: nodejs_version
    validations:
      required: true
    attributes:
      label: Version of Node.js
      placeholder: e.g. v10.23.0, v14.17.2
      description: >
        See "Info" Tab or use `node -v` via terminal
  - type: dropdown
    id: os
    validations:
      required: true
    attributes:
      label: Operating system
      options:
        - Linux
        - Windows
        - MacOS
        - Other
  - type: markdown
    attributes:
      value: |
        # Details / additional information
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful?
      description: >
        For example, error message, or stack traces
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
