name: Question
description: Ask a question
labels: [ Question ]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for questions only!
        If you have a problem please use the template for bug reports.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The question
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
